verbs = {
    "1": {"verb1": "run to", "verb2": "ran to", "s": "runs to", "ing": "running to"},
    "2": {"verb1": "go to", "verb2": "went to", "s": "goes to", "ing": "going to"},
    "3": {"verb1": "paint", "verb2": "painted", "s": "paints", "ing": "painting"},
    "4": {"verb1": "fly to", "verb2": "flew to", "s": "flies to", "ing": "flying to"},
    "5": {"verb1": "eat", "verb2": "ate", "s": "eats", "ing": "eating"},
    "6": {"verb1": "look at", "verb2": "looked at", "s": "looks at", "ing": "looking at"},
    "7": {"verb1": "dance at", "verb2": "danced at", "s": "dances at", "ing": "dancing at"},
    "8": {"verb1": "write", "verb2": "wrote", "s": "writes", "ing": "writing"},
    "9": {"verb1": "listen to", "verb2": "listened to", "s": "listens to", "ing": "listening to"},
    "10": {"verb1": "sing", "verb2": "sang", "s": "sings", "ing": "singing"},
    "11": {"verb1": "drink", "verb2": "drank", "s": "drinks", "ing": "drinking"},
    "12": {"verb1": "study", "verb2": "studied", "s": "studies", "ing": "studying"},
    "13": {"verb1": "play", "verb2": "played", "s": "plays", "ing": "playing"},
    "14": {"verb1": "sleep at", "verb2": "slept at", "s": "sleeps at", "ing": "sleeping at"},
    "15": {"verb1": "swim at", "verb2": "swam at", "s": "swims at", "ing": "swimming at"},
    "16": {"verb1": "call", "verb2": "called", "s": "calls", "ing": "calling"},
    "17": {"verb1": "watch", "verb2": "watched", "s": "watches", "ing": "watching"},
    "18": {"verb1": "read", "verb2": "read", "s": "reads", "ing": "reading"},
    "19": {"verb1": "talk", "verb2": "talked", "s": "talks", "ing": "talking"},
    "20": {"verb1": "think", "verb2": "thought", "s": "thinks", "ing": "thinking"},
    "21": {"verb1": "work", "verb2": "worked", "s": "works", "ing": "working"},
    "22": {"verb1": "run away", "verb2": "ran away", "s": "runs away", "ing": "running away"},
    "23": {"verb1": "climb", "verb2": "climbed", "s": "climbs", "ing": "climbing"},
    "24": {"verb1": "jump", "verb2": "jumped", "s": "jumps", "ing": "jumping"},
    "25": {"verb1": "laugh", "verb2": "laughed", "s": "laughs", "ing": "laughing"},
    "26": {"verb1": "cry", "verb2": "cried", "s": "cries", "ing": "crying"},
    "27": {"verb1": "run out of", "verb2": "ran out of", "s": "runs out of", "ing": "running out of"},
    "28": {"verb1": "build", "verb2": "built", "s": "builds", "ing": "building"},
    "29": {"verb1": "destroy", "verb2": "destroyed", "s": "destroys", "ing": "destroying"},
    "30": {"verb1": "discover", "verb2": "discovered", "s": "discovers", "ing": "discovering"},
    "31": {"verb1": "explore", "verb2": "explored", "s": "explores", "ing": "exploring"},
    "32": {"verb1": "create", "verb2": "created", "s": "creates", "ing": "creating"},
    "33": {"verb1": "travel to", "verb2": "traveled to", "s": "travels to", "ing": "traveling to"},
    "34": {"verb1": "surf", "verb2": "surfed", "s": "surfs", "ing": "surfing"},
    "35": {"verb1": "dance", "verb2": "danced", "s": "dances", "ing": "dancing"},
    "36": {"verb1": "eat out", "verb2": "ate out", "s": "eats out", "ing": "eating out"},
    "37": {"verb1": "cook", "verb2": "cooked", "s": "cooks", "ing": "cooking"},
    "38": {"verb1": "sing along", "verb2": "sang along", "s": "sings along", "ing": "singing along"},
    "39": {"verb1": "travel around", "verb2": "traveled around", "s": "travels around", "ing": "traveling around"},
    "40": {"verb1": "run after", "verb2": "ran after", "s": "runs after", "ing": "running after"},
    "41": {"verb1": "ride", "verb2": "rode", "s": "rides", "ing": "riding"},
    "42": {"verb1": "explore the world for", "verb2": "explored the world for", "s": "explores the world for", "ing": "exploring the world for"},
    "43": {"verb1": "fly high", "verb2": "flew high", "s": "flies high", "ing": "flying high"},
    "44": {"verb1": "run fast to", "verb2": "ran fast to", "s": "runs fast to", "ing": "running fast to"},
    "45": {"verb1": "paint a picture for", "verb2": "painted a picture for", "s": "paints a picture for", "ing": "painting a picture for"},
    "46": {"verb1": "write a story for", "verb2": "wrote a story for", "s": "writes a story for", "ing": "writing a story for"},
    "47": {"verb1": "listen carefully", "verb2": "listened carefully", "s": "listens carefully", "ing": "listening carefully"},
    "48": {"verb1": "read a book for", "verb2": "read a book for", "s": "reads a book for", "ing": "reading a book for"},
    "49": {"verb1": "talk loudly to", "verb2": "talked loudly to", "s": "talks loudly to", "ing": "talking loudly to"},
    "50": {"verb1": "work hard to", "verb2": "worked hard to", "s": "works hard to", "ing": "working hard to"},
}

subjects = {
    "1": {"s": "I", "vt": "am", "ns": "no"},
    "2": {"s": "You", "vt": "are", "ns": "no"},
    "3": {"s": "We", "vt": "are", "ns": "no"},
    "4": {"s": "They", "vt": "are", "ns": "no"},
    "5": {"s": "He", "vt": "is", "ns": "yes"},
    "6": {"s": "She", "vt": "is", "ns": "yes"},
    "7": {"s": "İt", "vt": "is", "ns": "yes"},
    "8": {"s": "John", "vt": "is", "ns": "yes"},
    "9": {"s": "Steve", "vt": "is", "ns": "yes"},
    "10": {"s": "the cat", "vt": "is", "ns": "yes"},
    "11": {"s": "the dog", "vt": "is", "ns": "yes"},
    "12": {"s": "a bird", "vt": "is", "ns": "yes"},
    "13": {"s": "the tree", "vt": "is", "ns": "yes"},
    "14": {"s": "a flower", "vt": "is", "ns": "yes"},
    "15": {"s": "my friend", "vt": "is", "ns": "yes"},
    "16": {"s": "a teacher", "vt": "is", "ns": "yes"},
    "17": {"s": "the ocean", "vt": "is", "ns": "yes"},
    "18": {"s": "a mountain", "vt": "is", "ns": "yes"},
    "19": {"s": "the sky", "vt": "is", "ns": "yes"},
    "20": {"s": "a cloud", "vt": "is", "ns": "yes"},
    "21": {"s": "the sun", "vt": "is", "ns": "yes"},
    "22": {"s": "a moon", "vt": "is", "ns": "yes"},
    "23": {"s": "the star", "vt": "is", "ns": "yes"},
    "24": {"s": "a planet", "vt": "is", "ns": "yes"},
    "25": {"s": "my sister", "vt": "is", "ns": "yes"},
    "26": {"s": "my brother", "vt": "is", "ns": "yes"},
    "27": {"s": "a house", "vt": "is", "ns": "yes"},
    "28": {"s": "a car", "vt": "is", "ns": "yes"},
    "29": {"s": "a bike", "vt": "is", "ns": "yes"},
    "30": {"s": "the forest", "vt": "is", "ns": "yes"},
    "31": {"s": "the river", "vt": "is", "ns": "yes"},
    "32": {"s": "the desert", "vt": "is", "ns": "yes"},
    "33": {"s": "a building", "vt": "is", "ns": "yes"},
    "34": {"s": "a street", "vt": "is", "ns": "yes"},
    "35": {"s": "my parents", "vt": "are", "ns": "no"},
    "36": {"s": "my grandparents", "vt": "are", "ns": "no"},
    "37": {"s": "the flowers", "vt": "are", "ns": "no"},
    "38": {"s": "the mountains", "vt": "are", "ns": "no"},
    "39": {"s": "the clouds", "vt": "are", "ns": "no"},
    "40": {"s": "the stars", "vt": "are", "ns": "no"},
    "41": {"s": "the planets", "vt": "are", "ns": "no"},
    "42": {"s": "the animals", "vt": "are", "ns": "no"},
    "43": {"s": "my classmates", "vt": "are", "ns": "no"},
    "44": {"s": "the students", "vt": "are", "ns": "no"},
    "45": {"s": "the teachers", "vt": "are", "ns": "no"},
    "46": {"s": "the books", "vt": "are", "ns": "no"},
    "47": {"s": "the movies", "vt": "are", "ns": "no"},
    "48": {"s": "the songs", "vt": "are", "ns": "no"},
    "49": {"s": "the games", "vt": "are", "ns": "no"},
    "50": {"s": "my dreams", "vt": "are", "ns": "no"},
    "51": {"s": "Olivia", "vt": "is", "ns": "yes"},
    "52": {"s": "Ethan", "vt": "is", "ns": "yes"},
    "53": {"s": "Ava", "vt": "is", "ns": "yes"},
    "54": {"s": "Liam", "vt": "is", "ns": "yes"},
    "55": {"s": "Emma", "vt": "is", "ns": "yes"},
    "56": {"s": "Jackson", "vt": "is", "ns": "yes"},
    "57": {"s": "Sophia", "vt": "is", "ns": "yes"},
    "58": {"s": "Mia", "vt": "is", "ns": "yes"},
    "59": {"s": "Lucas", "vt": "is", "ns": "yes"},
    "60": {"s": "Isabella", "vt": "is", "ns": "yes"},
    "61": {"s": "Aiden", "vt": "is", "ns": "yes"},
    "62": {"s": "Oliver", "vt": "is", "ns": "yes"},
    "63": {"s": "Sophie", "vt": "is", "ns": "yes"},
    "64": {"s": "Ella", "vt": "is", "ns": "yes"},
    "65": {"s": "Benjamin", "vt": "is", "ns": "yes"},
    "66": {"s": "Amelia", "vt": "is", "ns": "yes"},
    "67": {"s": "Henry", "vt": "is", "ns": "yes"},
    "68": {"s": "Avery", "vt": "is", "ns": "yes"},
    "69": {"s": "Mason", "vt": "is", "ns": "yes"},
    "70": {"s": "Abigail", "vt": "is", "ns": "yes"},
    "71": {"s": "Noah", "vt": "is", "ns": "yes"},
    "72": {"s": "Evelyn", "vt": "is", "ns": "yes"},
    "73": {"s": "William", "vt": "is", "ns": "yes"},
    "74": {"s": "Lily", "vt": "is", "ns": "yes"},
    "75": {"s": "James", "vt": "is", "ns": "yes"},
    "76": {"s": "Luna", "vt": "is", "ns": "yes"},
    "77": {"s": "Logan", "vt": "is", "ns": "yes"},
    "78": {"s": "Zoe", "vt": "is", "ns": "yes"},
    "79": {"s": "Alexander", "vt": "is", "ns": "yes"},
    "80": {"s": "Chloe", "vt": "is", "ns": "yes"},
    "81": {"s": "Michael", "vt": "is", "ns": "yes"},
    "82": {"s": "Grace", "vt": "is", "ns": "yes"},
    "83": {"s": "Daniel", "vt": "is", "ns": "yes"},
    "84": {"s": "Aubrey", "vt": "is", "ns": "yes"},
    "85": {"s": "Joseph", "vt": "is", "ns": "yes"},
    "86": {"s": "Penelope", "vt": "is", "ns": "yes"},
    "87": {"s": "David", "vt": "is", "ns": "yes"},
    "88": {"s": "Madison", "vt": "is", "ns": "yes"},
    "89": {"s": "Samuel", "vt": "is", "ns": "yes"},
    "90": {"s": "Scarlett", "vt": "is", "ns": "yes"},
    "91": {"s": "Nathan", "vt": "is", "ns": "yes"},
    "92": {"s": "Sofia", "vt": "is", "ns": "yes"},
    "93": {"s": "Christopher", "vt": "is", "ns": "yes"},
    "94": {"s": "Karl", "vt": "is", "ns": "yes"},
    "95": {"s": "Andrew", "vt": "is", "ns": "yes"},
    "96": {"s": "Aria", "vt": "is", "ns": "yes"},
    "97": {"s": "Matthew", "vt": "is", "ns": "yes"},
    "98": {"s": "Aiden", "vt": "is", "ns": "yes"},
    "99": {"s": "Nora", "vt": "is", "ns": "yes"},
    "100": {"s": "Jack", "vt": "is", "ns": "yes"},
}


times = {
    "past": {
        "1": "yesterday",
        "2": "last week",
        "3": "this morning",
        "4": "last month",
        "5": "last year",
        "6": "in 2023",
        "7": "in 2022",
        "8": "in 2021",
        "9": "in 2020",
        "10": "in 2019",
        "11": "last night",
        "12": "the day before yesterday",
        "13": "last friday",
        "14": "last saturday",
        "15": "two days ago",
        "16": "three weeks ago",
        "17": "yesterday morning",
        "18": "two months ago",
        "19": "five years ago",
        "20": "in 2018",
        "21": "last afternoon",
        "22": "four days ago",
        "23": "last month",
        "24": "last year",
        "25": "three years ago",
        "26": "",
    },
    "now": {
        "1": "now",
        "2": "today",
        "3": "right now",
        "4": "this week",
        "5": "since 1994",
        "6": "for 4 years",
        "7": "at this moment",
        "8": "currently",
        "9": "at present",
        "10": "in the present",
        "11": "at this time",
        "12": "currently",
        "13": "in the here and now",
        "14": "in this very moment",
        "15": "today morning",
        "16": "this very second",
        "17": "in the now",
        "18": "for the time being",
        "19": "this minute",
        "20": "today afternoon",
        "21": "at the present time",
        "22": "this exact moment",
        "23": "in the current moment",
        "24": "in the present moment",
        "25": "in the present day",
        "26": "",
    },
    "future": {
        "1": "tomorrow",
        "2": "the day after tomorrow",
        "3": "next week",
        "4": "next month",
        "5": "next year",
        "6": "in the future",
        "7": "in the coming days",
        "8": "in the upcoming weeks",
        "9": "in the near future",
        "10": "soon",
        "11": "in the next few months",
        "12": "in the upcoming year",
        "13": "in the forthcoming years",
        "14": "in the coming decade",
        "15": "next morning",
        "16": "next afternoon",
        "17": "next month",
        "18": "next year",
        "19": "in the next hour",
        "20": "in the coming weeks",
        "21": "the day following tomorrow",
        "22": "in the succeeding days",
        "23": "next friday",
        "24": "next saturday",
        "25": "next sunday",
        "26": "",
    },
}


objectsexperiemental = [
    "the wall",
    "the car",
    "hospital",
    "school",
    "apple",
    "watermelon",
    "world",
    "neptune",
    "the sun",
    "moon",
    "computer",
    "kitchen",
    "home",
    "airplane",
    "window",
    "door",
    "solar system",
    "park",
    "train station",
    "coffee cup",
    "bookshelf",
    "flower vase",
    "mountain",
    "ocean",
    "river",
    "library",
    "phone",
    "lamp",
    "television",
    "couch",
    "garden",
    "bicycle",
    "headphones",
    "camera",
    "pillow",
    "shoe rack",
    "backpack",
    "desk",
    "pen",
    "mirror",
    "umbrella",
    "beach",
    "lake",
    "forest",
    "bridge",
    "skyscraper",
    "city",
    "piano",
    "chair",
    "table",
    "painting",
    "sculpture",
    "train",
    "bus",
    "subway",
    "airport",
    "bus stop",
    "telephone booth",
    "coffee shop",
    "restaurant",
    "apartment",
    "swimming pool",
    "playground",
    "carousel",
    "ferris wheel",
    "roller coaster",
    "zoo",
    "museum",
    "fireplace",
    "tent",
    "tentacle",
    "cloud",
    "castle",
    "pyramid",
    "statue",
    "bridge",
    "tunnel",
    "light bulb",
    "globe",
    "spaceship",
    "rocket",
    "telescope",
    "volcano",
    "desert",
    "canyon",
    "waterfall",
    "giraffe",
    "penguin",
    "koala",
    "zebra",
    "tiger",
    "elephant",
    "dolphin",
    "butterfly",
    "peacock",
    "dragonfly",
    "robot",
    "wizard hat",
    "treasure chest",
    "magical wand",
    "time machine",
    "dimension portal",
    "galaxy",
    "comet",
    "meteor",
    "alien spaceship",
    "time capsule"
]
